// formats/singleRoundDraw.js
// The active default format ("Knockout" on the dashboard's Tournament
// Stage panel). Every sport's entrant pool is sized up to a proper
// knockout bracket (2, 4, 8, 16, 32... - the next power of two at or
// above the entrant count), generated by the constraint-based
// delegation-diversity matcher in core/delegationMatching.js.
//
// An entrant pool almost never lands exactly on a power of two, so
// whatever's left over once the pool is trimmed to an even bracket gets an
// explicit walk-in fixture (entrantB = "Walkin match", no delegation or
// other info attached) rather than silently advancing as an invisible
// bye - the schedule still shows a row for them (e.g. "Ammar Shehryar vs
// Walkin match"), it just books no venue/time slot, since core/
// venueAllocator.js already skips any match flagged `isWalkover`.
//
// Every format module in this folder exports the same shape:
//   generateSport(sportId, entrants, options) -> { rounds, byes, meta }
// where `rounds` is an array of "matchdays" (arrays of match objects), so
// the venue/time scheduler and the report builder don't need to know or
// care which format produced the fixtures.

import { generateMaxDiversityPairing } from '../core/delegationMatching.js';

let matchCounter = 0;

export function resetMatchCounter() {
  matchCounter = 0;
}

function nextMatchId() {
  matchCounter += 1;
  return `M${matchCounter}`;
}

/** Smallest power of two >= n (bracket sizes only ever come in 2, 4, 8, 16, 32...). */
function nextPowerOfTwo(n) {
  let p = 1;
  while (p < n) p *= 2;
  return p;
}

function walkinOpponent() {
  return { id: 'WALKIN', name: 'Walkin match', delegation: '', isWalkin: true };
}

/**
 * Pick `count` entrants to receive a walk-in fixture instead of a real
 * opponent, drawing preferentially from whichever delegation currently has
 * the most entrants left so walk-ins don't all land inside one small
 * delegation. Returns the chosen entrants plus everyone else - always an
 * even-sized pool, so the diversity pairing below never needs to produce
 * a bye of its own.
 */
function pickWalkins(entrants, count) {
  if (count <= 0) return { walkins: [], remaining: entrants };
  const groups = new Map();
  for (const e of entrants) {
    if (!groups.has(e.delegation)) groups.set(e.delegation, []);
    groups.get(e.delegation).push(e);
  }
  const buckets = [...groups.values()];
  const walkins = [];
  while (walkins.length < count) {
    buckets.sort((a, b) => b.length - a.length);
    const biggest = buckets.find((g) => g.length > 0);
    if (!biggest) break; // shouldn't happen - count is always <= entrants.length
    walkins.push(biggest.pop());
  }
  const walkinIds = new Set(walkins.map((w) => w.id));
  const remaining = entrants.filter((e) => !walkinIds.has(e.id));
  return { walkins, remaining };
}

export function generateSport(sportId, entrants) {
  const total = entrants.length;
  const bracketSize = total > 0 ? nextPowerOfTwo(total) : 0;
  const walkinCount = bracketSize - total;

  const { walkins, remaining } = pickWalkins(entrants, walkinCount);
  const { pairs, byes } = generateMaxDiversityPairing(remaining);

  const matches = pairs.map(({ a, b, sameDelegation }) => ({
    id: nextMatchId(),
    sport: sportId,
    entrantA: a,
    entrantB: b,
    clash: sameDelegation ? a.delegation : null,
  }));

  for (const entrant of walkins) {
    matches.push({
      id: nextMatchId(),
      sport: sportId,
      entrantA: entrant,
      entrantB: walkinOpponent(),
      clash: null,
      isWalkover: true,
    });
  }

  return {
    rounds: matches.length ? [matches] : [],
    byes,
    meta: {
      format: 'singleRoundDraw',
      totalEntrants: total,
      bracketSize,
      walkinCount: walkins.length,
      fixtureCount: matches.length,
    },
  };
}
